/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;



/**
 *
 * @author Elton
 */
public class painelCal extends javax.swing.JFrame {

 String temporaria ="";
 String operacao ="";
 double a= 0;
 double b= 0;
 double resultado;

    /**
     * Creates new form painelCal
     */
    public painelCal() {
        initComponents();
       
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bResultado = new javax.swing.JButton();
        bNove = new javax.swing.JButton();
        bMultiplicacao = new javax.swing.JButton();
        bTres = new javax.swing.JButton();
        bZero = new javax.swing.JButton();
        bDiminuir = new javax.swing.JButton();
        bCinco = new javax.swing.JButton();
        bDivisao = new javax.swing.JButton();
        bSeis = new javax.swing.JButton();
        bSoma = new javax.swing.JButton();
        telinha = new javax.swing.JTextField();
        bDois = new javax.swing.JButton();
        bSete = new javax.swing.JButton();
        bOito = new javax.swing.JButton();
        bUm = new javax.swing.JButton();
        bQuatro = new javax.swing.JButton();
        bPonto = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bPotencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bResultado.setText("=");
        bResultado.setPreferredSize(new java.awt.Dimension(25, 25));
        bResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResultadoActionPerformed(evt);
            }
        });

        bNove.setText("9");
        bNove.setPreferredSize(new java.awt.Dimension(25, 25));
        bNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoveActionPerformed(evt);
            }
        });

        bMultiplicacao.setText("*");
        bMultiplicacao.setPreferredSize(new java.awt.Dimension(25, 25));
        bMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiplicacaoActionPerformed(evt);
            }
        });

        bTres.setText("3");
        bTres.setPreferredSize(new java.awt.Dimension(25, 25));
        bTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTresActionPerformed(evt);
            }
        });

        bZero.setText("0");
        bZero.setPreferredSize(new java.awt.Dimension(25, 25));
        bZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZeroActionPerformed(evt);
            }
        });

        bDiminuir.setText("-");
        bDiminuir.setPreferredSize(new java.awt.Dimension(25, 25));
        bDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiminuirActionPerformed(evt);
            }
        });

        bCinco.setText("5");
        bCinco.setPreferredSize(new java.awt.Dimension(25, 25));
        bCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCincoActionPerformed(evt);
            }
        });

        bDivisao.setText("/");
        bDivisao.setPreferredSize(new java.awt.Dimension(25, 25));
        bDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivisaoActionPerformed(evt);
            }
        });

        bSeis.setText("6");
        bSeis.setPreferredSize(new java.awt.Dimension(25, 25));
        bSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeisActionPerformed(evt);
            }
        });

        bSoma.setText("+ ");
        bSoma.setPreferredSize(new java.awt.Dimension(25, 25));
        bSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSomaActionPerformed(evt);
            }
        });

        telinha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        bDois.setText("2");
        bDois.setPreferredSize(new java.awt.Dimension(25, 25));
        bDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDoisActionPerformed(evt);
            }
        });

        bSete.setText("7");
        bSete.setPreferredSize(new java.awt.Dimension(25, 25));
        bSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeteActionPerformed(evt);
            }
        });

        bOito.setText("8");
        bOito.setPreferredSize(new java.awt.Dimension(25, 25));
        bOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOitoActionPerformed(evt);
            }
        });

        bUm.setText("1");
        bUm.setPreferredSize(new java.awt.Dimension(25, 25));
        bUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUmActionPerformed(evt);
            }
        });

        bQuatro.setText("4");
        bQuatro.setPreferredSize(new java.awt.Dimension(25, 25));
        bQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuatroActionPerformed(evt);
            }
        });

        bPonto.setText(".");
        bPonto.setPreferredSize(new java.awt.Dimension(25, 25));
        bPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPontoActionPerformed(evt);
            }
        });

        bReset.setText("C");
        bReset.setPreferredSize(new java.awt.Dimension(25, 25));
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bPotencia.setText("^");
        bPotencia.setPreferredSize(new java.awt.Dimension(25, 25));
        bPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPotenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bSete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bDiminuir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bPonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bDivisao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(bReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bOito, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(bResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bUm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCinco, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(bDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSeis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bNove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(telinha))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(telinha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDois, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTres, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOito, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNove, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDiminuir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bZero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUmActionPerformed
         digNumero("1");  
    }//GEN-LAST:event_bUmActionPerformed

    private void bDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDoisActionPerformed
  digNumero("2"); 
    }//GEN-LAST:event_bDoisActionPerformed

    private void bTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTresActionPerformed
     digNumero("3");  
    }//GEN-LAST:event_bTresActionPerformed

    private void bQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuatroActionPerformed
     digNumero("4"); 
    }//GEN-LAST:event_bQuatroActionPerformed

    private void bCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCincoActionPerformed
    digNumero("5"); 
    }//GEN-LAST:event_bCincoActionPerformed

    private void bSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeisActionPerformed
  digNumero("6"); 
    }//GEN-LAST:event_bSeisActionPerformed

    private void bSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeteActionPerformed
     digNumero("7"); 
    }//GEN-LAST:event_bSeteActionPerformed

    private void bOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOitoActionPerformed
        digNumero("8"); 
    }//GEN-LAST:event_bOitoActionPerformed

    private void bNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoveActionPerformed
         digNumero("9");  
    }//GEN-LAST:event_bNoveActionPerformed

    private void bResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResultadoActionPerformed
        digNumero("= "+ resultado); 
      
        calculos(); 
        
        
       
    }//GEN-LAST:event_bResultadoActionPerformed

    private void bZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZeroActionPerformed
     digNumero("0"); 
    }//GEN-LAST:event_bZeroActionPerformed

    private void bDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiminuirActionPerformed
        digNumero("-");
        numeroA();
          operacao="-";    
    }//GEN-LAST:event_bDiminuirActionPerformed

    private void bDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivisaoActionPerformed
        digNumero("/"); 
        numeroA();
           operacao="/";
    }//GEN-LAST:event_bDivisaoActionPerformed

    private void bMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiplicacaoActionPerformed
       digNumero("*");
       numeroA();
        operacao= "*";
     
    }//GEN-LAST:event_bMultiplicacaoActionPerformed

    private void bSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSomaActionPerformed

       numeroA();
      operacao = "+";
      digNumero("+");
    }//GEN-LAST:event_bSomaActionPerformed

    

    private void bPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPontoActionPerformed
         digNumero("."); 
          
    }//GEN-LAST:event_bPontoActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
       
       telinha.setText(String.valueOf(" "));
       
    }//GEN-LAST:event_bResetActionPerformed

    private void bPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPotenciaActionPerformed
        digNumero("^");
        
    }//GEN-LAST:event_bPotenciaActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(painelCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(painelCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(painelCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(painelCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new painelCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCinco;
    private javax.swing.JButton bDiminuir;
    private javax.swing.JButton bDivisao;
    private javax.swing.JButton bDois;
    private javax.swing.JButton bMultiplicacao;
    private javax.swing.JButton bNove;
    private javax.swing.JButton bOito;
    private javax.swing.JButton bPonto;
    private javax.swing.JButton bPotencia;
    private javax.swing.JButton bQuatro;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bResultado;
    private javax.swing.JButton bSeis;
    private javax.swing.JButton bSete;
    private javax.swing.JButton bSoma;
    private javax.swing.JButton bTres;
    private javax.swing.JButton bUm;
    private javax.swing.JButton bZero;
    private javax.swing.JTextField telinha;
    // End of variables declaration//GEN-END:variables
public void  digNumero(String numero ) {
        temporaria = telinha.getText();
        temporaria = temporaria + numero;
        telinha.setText(temporaria);
    }
   public void numeroA() {
     a =Double.parseDouble(telinha.getText());
       
     } 
public void numeroB(){
     b =Double.parseDouble(telinha.getText()); 
}
private  void calculos (){
   if( a !=0 && b!= 0){
       
    if(operacao == "+"){
         resultado= a+b;
      }
    else if(operacao ==" -"){
        resultado = a-b;
    }
    else if(operacao ==" *"){
        resultado = a*b;
    }
    else if(operacao ==" /"){
        resultado = a / b;
    }
    resultado =Double.parseDouble(telinha.getText());
    telinha.setText(""+ resultado);   
}  
}

}
